version: '3'
services:
  site:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=development

  build:
    build: .
    command: bundle exec jekyll build --destination _site
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=production
